name: Run tests
run-name: Run tests - ${{ github.sha }}
on: push
jobs:
  run_test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, macos-14]
        py: [3.8, 3.9, 3.10, 3.11, 3.12]
    name: Python ${{ matrix.py }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Download data
        working-directory: tests
        run: |
          curl -L -O https://github.com/daducci/COMMIT/wiki/files/demo01_data.zip
          curl -L -O https://github.com/daducci/COMMIT/wiki/files/demo01_fibers.tck
          7z x demo01_data.zip
          mv demo01_fibers.tck demo01_data
      - name: Set up Python ${{ matrix.py }}
        uses: actions/setup-python@v5.0.0
        with:
          python-version: ${{ matrix.py }}
      - name: Install dmri-commit
        run: pip install . --no-cache-dir --force-reinstall
      - name: Run tests
        working-directory: tests
        run: |
          echo "Run tests"
      - name: Done
        run: |
          echo "All tests passed!"
